const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const MARK_COMPLETED = 'MARK_COMPLETED';
const MARK_ACTIVE = 'MARK_ACTIVE';

const ADD_FOLDER = 'ADD_FOLDER';
const DELETE_FOLDER = 'DELETE_FOLDER';

const SET_DEVICE = 'SET_DEVICE';
const SET_THEME = 'SET_THEME';
const TOGGLE_THEME = 'TOGGLE_THEME';
const SET_FOLDER_FILTER = 'SET_FOLDER_FILTER';
const SET_STATUS_FILTER = 'SET_STATUS_FILTER';
const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
const SET_CURRENT_CHOSEN_DATE = 'SET_CURRENT_CHOSEN_DATE';

const SET_IS_MODE_ON = 'SET_IS_MODE_ON';
const SET_NEW_TODO_DATA = 'SET_NEW_TODO_DATA';
const SET_NEW_FOLDER_DATA = 'SET_NEW_FOLDER_DATA';
const SET_POPUP_DATA = 'SET_POPUP_DATA';

export {
  ADD_TODO,
  DELETE_TODO,
  MARK_COMPLETED,
  MARK_ACTIVE,

  ADD_FOLDER,
  DELETE_FOLDER,

  SET_DEVICE,
  SET_THEME,
  TOGGLE_THEME,
  SET_FOLDER_FILTER,
  SET_STATUS_FILTER,
  SET_WINDOW_SIZE,
  SET_CURRENT_CHOSEN_DATE,

  SET_IS_MODE_ON,
  SET_NEW_TODO_DATA,
  SET_NEW_FOLDER_DATA,
  SET_POPUP_DATA,
};
